// Callsign prefix -> country lookup table for the FT8 Decoder panel's
// "Country" column. Manually compiled from the ITU's Table of International
// Call Sign Series (Appendix 42 to the Radio Regulations) and standard,
// textbook ham-radio prefix-block knowledge — NOT derived from or copied
// from any third party's compiled database (e.g. AD1C's cty.dat, the
// contest-logging industry standard, whose redistribution terms couldn't be
// confirmed). Deliberately not an exhaustive ~340-entity DXCC list — covers
// the major, commonly-heard-on-the-air countries/territories. Matched via a
// plain longest-prefix `callsign.startsWith(entry.prefix)` in
// src/ft8Callsign.ts, so entries needn't be sorted; more specific (longer)
// prefixes automatically take precedence over shorter ones that would
// otherwise also match (e.g. "KH6" for Hawaii over the general "K" for the
// United States).
export interface DxccPrefixEntry {
  prefix: string;
  country: string;
  flag: string;
}

export const DXCC_PREFIXES: DxccPrefixEntry[] = [
  // --- North America ---
  { prefix: 'K', country: 'United States', flag: '🇺🇸' },
  { prefix: 'W', country: 'United States', flag: '🇺🇸' },
  { prefix: 'N', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AA', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AB', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AC', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AD', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AE', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AF', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AG', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AI', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AJ', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AK', country: 'United States', flag: '🇺🇸' },
  { prefix: 'AL', country: 'United States', flag: '🇺🇸' },
  { prefix: 'KL', country: 'Alaska', flag: '🇺🇸' },
  { prefix: 'KH6', country: 'Hawaii', flag: '🇺🇸' },
  { prefix: 'KH7', country: 'Hawaii', flag: '🇺🇸' },
  { prefix: 'KH0', country: 'Northern Mariana Islands', flag: '🇲🇵' },
  { prefix: 'KH1', country: 'Baker & Howland Islands', flag: '🇺🇸' },
  { prefix: 'KH2', country: 'Guam', flag: '🇬🇺' },
  { prefix: 'KH3', country: 'Johnston Island', flag: '🇺🇸' },
  { prefix: 'KH4', country: 'Midway Island', flag: '🇺🇸' },
  { prefix: 'KH5', country: 'Palmyra & Jarvis Islands', flag: '🇺🇸' },
  { prefix: 'KH8', country: 'American Samoa', flag: '🇦🇸' },
  { prefix: 'KH9', country: 'Wake Island', flag: '🇺🇸' },
  { prefix: 'KP1', country: 'Navassa Island', flag: '🇺🇸' },
  { prefix: 'KP2', country: 'US Virgin Islands', flag: '🇻🇮' },
  { prefix: 'KP3', country: 'Puerto Rico', flag: '🇵🇷' },
  { prefix: 'KP4', country: 'Puerto Rico', flag: '🇵🇷' },
  { prefix: 'KP5', country: 'Desecheo Island', flag: '🇵🇷' },
  { prefix: 'VE', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'VA', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'VO', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'VY', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'VX', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'CF', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'CG', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'CH', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'CI', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'CJ', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'CK', country: 'Canada', flag: '🇨🇦' },
  { prefix: 'CY0', country: 'Sable Island', flag: '🇨🇦' },
  { prefix: 'CY9', country: 'St. Paul Island', flag: '🇨🇦' },
  { prefix: 'XE', country: 'Mexico', flag: '🇲🇽' },
  { prefix: 'XF', country: 'Mexico', flag: '🇲🇽' },
  { prefix: 'XA', country: 'Mexico', flag: '🇲🇽' },
  { prefix: 'XB', country: 'Mexico', flag: '🇲🇽' },
  { prefix: 'XC', country: 'Mexico', flag: '🇲🇽' },
  { prefix: 'CO', country: 'Cuba', flag: '🇨🇺' },
  { prefix: 'CM', country: 'Cuba', flag: '🇨🇺' },
  { prefix: 'T4', country: 'Cuba', flag: '🇨🇺' },
  { prefix: 'HI', country: 'Dominican Republic', flag: '🇩🇴' },
  { prefix: '6Y', country: 'Jamaica', flag: '🇯🇲' },
  { prefix: 'C6', country: 'Bahamas', flag: '🇧🇸' },
  { prefix: 'HH', country: 'Haiti', flag: '🇭🇹' },
  { prefix: '9Y', country: 'Trinidad & Tobago', flag: '🇹🇹' },
  { prefix: '9Z', country: 'Trinidad & Tobago', flag: '🇹🇹' },
  { prefix: '8P', country: 'Barbados', flag: '🇧🇧' },
  { prefix: 'P4', country: 'Aruba', flag: '🇦🇼' },
  { prefix: 'PJ2', country: 'Curaçao', flag: '🇨🇼' },
  { prefix: 'PJ4', country: 'Bonaire', flag: '🇧🇶' },
  { prefix: 'PJ7', country: 'Sint Maarten', flag: '🇸🇽' },
  { prefix: 'FG', country: 'Guadeloupe', flag: '🇬🇵' },
  { prefix: 'FM', country: 'Martinique', flag: '🇲🇶' },
  { prefix: 'FS', country: 'Saint Martin', flag: '🇲🇫' },
  { prefix: 'FJ', country: 'Saint Barthélemy', flag: '🇧🇱' },
  { prefix: 'TI', country: 'Costa Rica', flag: '🇨🇷' },
  { prefix: 'HP', country: 'Panama', flag: '🇵🇦' },
  { prefix: 'HO', country: 'Panama', flag: '🇵🇦' },
  { prefix: 'TG', country: 'Guatemala', flag: '🇬🇹' },
  { prefix: 'HR', country: 'Honduras', flag: '🇭🇳' },
  { prefix: 'YS', country: 'El Salvador', flag: '🇸🇻' },
  { prefix: 'YN', country: 'Nicaragua', flag: '🇳🇮' },
  { prefix: 'V3', country: 'Belize', flag: '🇧🇿' },
  { prefix: 'ZF', country: 'Cayman Islands', flag: '🇰🇾' },
  { prefix: 'VP5', country: 'Turks & Caicos', flag: '🇹🇨' },
  { prefix: 'VP2V', country: 'British Virgin Islands', flag: '🇻🇬' },
  { prefix: 'VP2E', country: 'Anguilla', flag: '🇦🇮' },
  { prefix: 'VP2M', country: 'Montserrat', flag: '🇲🇸' },
  { prefix: 'V2', country: 'Antigua & Barbuda', flag: '🇦🇬' },
  { prefix: 'V4', country: 'St. Kitts & Nevis', flag: '🇰🇳' },
  { prefix: 'J6', country: 'St. Lucia', flag: '🇱🇨' },
  { prefix: 'J8', country: 'St. Vincent', flag: '🇻🇨' },
  { prefix: 'J3', country: 'Grenada', flag: '🇬🇩' },
  { prefix: 'J7', country: 'Dominica', flag: '🇩🇲' },
  { prefix: 'OX', country: 'Greenland', flag: '🇬🇱' },

  // --- South America ---
  { prefix: 'PY', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'PP', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'PQ', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'PR', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'PS', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'PT', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'PU', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'PV', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'PW', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'ZV', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'ZW', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'ZX', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'ZY', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'ZZ', country: 'Brazil', flag: '🇧🇷' },
  { prefix: 'LU', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'LW', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'LO', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'LP', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'LQ', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'LR', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'LS', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'LT', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'LV', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'AY', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'AZ', country: 'Argentina', flag: '🇦🇷' },
  { prefix: 'CE', country: 'Chile', flag: '🇨🇱' },
  { prefix: 'CA', country: 'Chile', flag: '🇨🇱' },
  { prefix: 'CB', country: 'Chile', flag: '🇨🇱' },
  { prefix: 'CD', country: 'Chile', flag: '🇨🇱' },
  { prefix: 'XR', country: 'Chile', flag: '🇨🇱' },
  { prefix: 'OA', country: 'Peru', flag: '🇵🇪' },
  { prefix: 'OB', country: 'Peru', flag: '🇵🇪' },
  { prefix: 'OC', country: 'Peru', flag: '🇵🇪' },
  { prefix: 'HK', country: 'Colombia', flag: '🇨🇴' },
  { prefix: 'HJ', country: 'Colombia', flag: '🇨🇴' },
  { prefix: '5J', country: 'Colombia', flag: '🇨🇴' },
  { prefix: '5K', country: 'Colombia', flag: '🇨🇴' },
  { prefix: 'YV', country: 'Venezuela', flag: '🇻🇪' },
  { prefix: 'YW', country: 'Venezuela', flag: '🇻🇪' },
  { prefix: 'YX', country: 'Venezuela', flag: '🇻🇪' },
  { prefix: 'YY', country: 'Venezuela', flag: '🇻🇪' },
  { prefix: 'HC', country: 'Ecuador', flag: '🇪🇨' },
  { prefix: 'HD', country: 'Ecuador', flag: '🇪🇨' },
  { prefix: 'CP', country: 'Bolivia', flag: '🇧🇴' },
  { prefix: 'ZP', country: 'Paraguay', flag: '🇵🇾' },
  { prefix: 'CX', country: 'Uruguay', flag: '🇺🇾' },
  { prefix: 'CV', country: 'Uruguay', flag: '🇺🇾' },
  { prefix: '8R', country: 'Guyana', flag: '🇬🇾' },
  { prefix: 'PZ', country: 'Suriname', flag: '🇸🇷' },
  { prefix: 'FY', country: 'French Guiana', flag: '🇬🇫' },
  { prefix: 'VP8', country: 'Falkland Islands', flag: '🇫🇰' },

  // --- Europe ---
  { prefix: 'GM', country: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { prefix: 'MM', country: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { prefix: 'GW', country: 'Wales', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { prefix: 'MW', country: 'Wales', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { prefix: 'GI', country: 'Northern Ireland', flag: '🇬🇧' },
  { prefix: 'MI', country: 'Northern Ireland', flag: '🇬🇧' },
  { prefix: 'GD', country: 'Isle of Man', flag: '🇮🇲' },
  { prefix: 'MD', country: 'Isle of Man', flag: '🇮🇲' },
  { prefix: 'GU', country: 'Guernsey', flag: '🇬🇬' },
  { prefix: 'MU', country: 'Guernsey', flag: '🇬🇬' },
  { prefix: 'GJ', country: 'Jersey', flag: '🇯🇪' },
  { prefix: 'MJ', country: 'Jersey', flag: '🇯🇪' },
  { prefix: 'G', country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { prefix: 'M', country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { prefix: '2E', country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { prefix: 'EI', country: 'Ireland', flag: '🇮🇪' },
  { prefix: 'EJ', country: 'Ireland', flag: '🇮🇪' },
  { prefix: 'DL', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DA', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DB', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DC', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DD', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DF', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DG', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DH', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DJ', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DK', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DM', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'DO', country: 'Germany', flag: '🇩🇪' },
  { prefix: 'F', country: 'France', flag: '🇫🇷' },
  { prefix: 'TM', country: 'France', flag: '🇫🇷' },
  { prefix: 'I', country: 'Italy', flag: '🇮🇹' },
  { prefix: 'EA', country: 'Spain', flag: '🇪🇸' },
  { prefix: 'EB', country: 'Spain', flag: '🇪🇸' },
  { prefix: 'EC', country: 'Spain', flag: '🇪🇸' },
  { prefix: 'ED', country: 'Spain', flag: '🇪🇸' },
  { prefix: 'EE', country: 'Spain', flag: '🇪🇸' },
  { prefix: 'EF', country: 'Spain', flag: '🇪🇸' },
  { prefix: 'EA6', country: 'Balearic Islands', flag: '🇪🇸' },
  { prefix: 'EA8', country: 'Canary Islands', flag: '🇮🇨' },
  { prefix: 'EA9', country: 'Ceuta & Melilla', flag: '🇪🇸' },
  { prefix: 'CT', country: 'Portugal', flag: '🇵🇹' },
  { prefix: 'CT3', country: 'Madeira', flag: '🇵🇹' },
  { prefix: 'CU', country: 'Azores', flag: '🇵🇹' },
  { prefix: 'PA', country: 'Netherlands', flag: '🇳🇱' },
  { prefix: 'PB', country: 'Netherlands', flag: '🇳🇱' },
  { prefix: 'PC', country: 'Netherlands', flag: '🇳🇱' },
  { prefix: 'PD', country: 'Netherlands', flag: '🇳🇱' },
  { prefix: 'PE', country: 'Netherlands', flag: '🇳🇱' },
  { prefix: 'PF', country: 'Netherlands', flag: '🇳🇱' },
  { prefix: 'PG', country: 'Netherlands', flag: '🇳🇱' },
  { prefix: 'PH', country: 'Netherlands', flag: '🇳🇱' },
  { prefix: 'PI', country: 'Netherlands', flag: '🇳🇱' },
  { prefix: 'ON', country: 'Belgium', flag: '🇧🇪' },
  { prefix: 'OO', country: 'Belgium', flag: '🇧🇪' },
  { prefix: 'OP', country: 'Belgium', flag: '🇧🇪' },
  { prefix: 'OQ', country: 'Belgium', flag: '🇧🇪' },
  { prefix: 'OR', country: 'Belgium', flag: '🇧🇪' },
  { prefix: 'OS', country: 'Belgium', flag: '🇧🇪' },
  { prefix: 'OT', country: 'Belgium', flag: '🇧🇪' },
  { prefix: 'LX', country: 'Luxembourg', flag: '🇱🇺' },
  { prefix: 'HB9', country: 'Switzerland', flag: '🇨🇭' },
  { prefix: 'HB0', country: 'Liechtenstein', flag: '🇱🇮' },
  { prefix: 'OE', country: 'Austria', flag: '🇦🇹' },
  { prefix: 'SM', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SA', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SB', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SC', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SD', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SE', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SF', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SG', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SH', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SI', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SJ', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SK', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'SL', country: 'Sweden', flag: '🇸🇪' },
  { prefix: 'LA', country: 'Norway', flag: '🇳🇴' },
  { prefix: 'LB', country: 'Norway', flag: '🇳🇴' },
  { prefix: 'LJ', country: 'Norway', flag: '🇳🇴' },
  { prefix: 'LN', country: 'Norway', flag: '🇳🇴' },
  { prefix: 'JW', country: 'Svalbard', flag: '🇸🇯' },
  { prefix: 'JX', country: 'Jan Mayen', flag: '🇳🇴' },
  { prefix: 'OZ', country: 'Denmark', flag: '🇩🇰' },
  { prefix: 'OU', country: 'Denmark', flag: '🇩🇰' },
  { prefix: 'OV', country: 'Denmark', flag: '🇩🇰' },
  { prefix: 'OW', country: 'Denmark', flag: '🇩🇰' },
  { prefix: '5P', country: 'Denmark', flag: '🇩🇰' },
  { prefix: '5Q', country: 'Denmark', flag: '🇩🇰' },
  { prefix: 'OH', country: 'Finland', flag: '🇫🇮' },
  { prefix: 'OF', country: 'Finland', flag: '🇫🇮' },
  { prefix: 'OG', country: 'Finland', flag: '🇫🇮' },
  { prefix: 'OJ0', country: 'Market Reef', flag: '🇫🇮' },
  { prefix: 'TF', country: 'Iceland', flag: '🇮🇸' },
  { prefix: 'HA', country: 'Hungary', flag: '🇭🇺' },
  { prefix: 'HG', country: 'Hungary', flag: '🇭🇺' },
  { prefix: 'OK', country: 'Czech Republic', flag: '🇨🇿' },
  { prefix: 'OL', country: 'Czech Republic', flag: '🇨🇿' },
  { prefix: 'OM', country: 'Slovakia', flag: '🇸🇰' },
  { prefix: 'SP', country: 'Poland', flag: '🇵🇱' },
  { prefix: 'SN', country: 'Poland', flag: '🇵🇱' },
  { prefix: 'SO', country: 'Poland', flag: '🇵🇱' },
  { prefix: 'SQ', country: 'Poland', flag: '🇵🇱' },
  { prefix: 'SR', country: 'Poland', flag: '🇵🇱' },
  { prefix: 'YO', country: 'Romania', flag: '🇷🇴' },
  { prefix: 'YP', country: 'Romania', flag: '🇷🇴' },
  { prefix: 'YQ', country: 'Romania', flag: '🇷🇴' },
  { prefix: 'YR', country: 'Romania', flag: '🇷🇴' },
  { prefix: 'LZ', country: 'Bulgaria', flag: '🇧🇬' },
  { prefix: '9A', country: 'Croatia', flag: '🇭🇷' },
  { prefix: 'S5', country: 'Slovenia', flag: '🇸🇮' },
  { prefix: 'E7', country: 'Bosnia & Herzegovina', flag: '🇧🇦' },
  { prefix: 'YU', country: 'Serbia', flag: '🇷🇸' },
  { prefix: 'YT', country: 'Serbia', flag: '🇷🇸' },
  { prefix: '4O', country: 'Montenegro', flag: '🇲🇪' },
  { prefix: 'Z3', country: 'North Macedonia', flag: '🇲🇰' },
  { prefix: 'ZA', country: 'Albania', flag: '🇦🇱' },
  { prefix: 'SV', country: 'Greece', flag: '🇬🇷' },
  { prefix: 'SW', country: 'Greece', flag: '🇬🇷' },
  { prefix: 'SX', country: 'Greece', flag: '🇬🇷' },
  { prefix: 'SY', country: 'Greece', flag: '🇬🇷' },
  { prefix: 'SZ', country: 'Greece', flag: '🇬🇷' },
  { prefix: 'SV9', country: 'Crete', flag: '🇬🇷' },
  { prefix: 'SV5', country: 'Dodecanese', flag: '🇬🇷' },
  { prefix: 'SV8', country: 'Dodecanese', flag: '🇬🇷' },
  { prefix: 'ER', country: 'Moldova', flag: '🇲🇩' },
  { prefix: 'UR', country: 'Ukraine', flag: '🇺🇦' },
  { prefix: 'US', country: 'Ukraine', flag: '🇺🇦' },
  { prefix: 'UT', country: 'Ukraine', flag: '🇺🇦' },
  { prefix: 'UU', country: 'Ukraine', flag: '🇺🇦' },
  { prefix: 'UW', country: 'Ukraine', flag: '🇺🇦' },
  { prefix: 'UX', country: 'Ukraine', flag: '🇺🇦' },
  { prefix: 'UY', country: 'Ukraine', flag: '🇺🇦' },
  { prefix: 'UZ', country: 'Ukraine', flag: '🇺🇦' },
  { prefix: 'EW', country: 'Belarus', flag: '🇧🇾' },
  { prefix: 'EU', country: 'Belarus', flag: '🇧🇾' },
  { prefix: 'EV', country: 'Belarus', flag: '🇧🇾' },
  { prefix: 'YL', country: 'Latvia', flag: '🇱🇻' },
  { prefix: 'LY', country: 'Lithuania', flag: '🇱🇹' },
  { prefix: 'ES', country: 'Estonia', flag: '🇪🇪' },
  { prefix: '9H', country: 'Malta', flag: '🇲🇹' },
  { prefix: 'C3', country: 'Andorra', flag: '🇦🇩' },
  { prefix: '3A', country: 'Monaco', flag: '🇲🇨' },
  { prefix: 'T7', country: 'San Marino', flag: '🇸🇲' },
  { prefix: 'HV', country: 'Vatican', flag: '🇻🇦' },

  // --- Russia / Central Asia / Caucasus ---
  { prefix: 'R', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'UA', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'UB', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'UC', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'UD', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'UE', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'UF', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'UG', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'UH', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'UI', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'RA', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'RK', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'RM', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'RN', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'RU', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'RV', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'RW', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'RX', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'RZ', country: 'Russia', flag: '🇷🇺' },
  { prefix: 'RA0', country: 'Asiatic Russia', flag: '🇷🇺' },
  { prefix: 'RA9', country: 'Asiatic Russia', flag: '🇷🇺' },
  { prefix: 'UN', country: 'Kazakhstan', flag: '🇰🇿' },
  { prefix: 'UO', country: 'Kazakhstan', flag: '🇰🇿' },
  { prefix: 'UP', country: 'Kazakhstan', flag: '🇰🇿' },
  { prefix: 'EY', country: 'Tajikistan', flag: '🇹🇯' },
  { prefix: 'EX', country: 'Kyrgyzstan', flag: '🇰🇬' },
  { prefix: 'UJ', country: 'Uzbekistan', flag: '🇺🇿' },
  { prefix: 'UK', country: 'Uzbekistan', flag: '🇺🇿' },
  { prefix: 'EZ', country: 'Turkmenistan', flag: '🇹🇲' },
  { prefix: '4L', country: 'Georgia', flag: '🇬🇪' },
  { prefix: '4J', country: 'Azerbaijan', flag: '🇦🇿' },
  { prefix: '4K', country: 'Azerbaijan', flag: '🇦🇿' },
  { prefix: 'EK', country: 'Armenia', flag: '🇦🇲' },

  // --- Middle East ---
  { prefix: 'TA', country: 'Turkey', flag: '🇹🇷' },
  { prefix: 'TB', country: 'Turkey', flag: '🇹🇷' },
  { prefix: 'TC', country: 'Turkey', flag: '🇹🇷' },
  { prefix: '4X', country: 'Israel', flag: '🇮🇱' },
  { prefix: '4Z', country: 'Israel', flag: '🇮🇱' },
  { prefix: 'JY', country: 'Jordan', flag: '🇯🇴' },
  { prefix: 'OD', country: 'Lebanon', flag: '🇱🇧' },
  { prefix: 'YK', country: 'Syria', flag: '🇸🇾' },
  { prefix: 'A4', country: 'Oman', flag: '🇴🇲' },
  { prefix: 'A6', country: 'United Arab Emirates', flag: '🇦🇪' },
  { prefix: 'A7', country: 'Qatar', flag: '🇶🇦' },
  { prefix: 'A9', country: 'Bahrain', flag: '🇧🇭' },
  { prefix: '9K', country: 'Kuwait', flag: '🇰🇼' },
  { prefix: 'HZ', country: 'Saudi Arabia', flag: '🇸🇦' },
  { prefix: '7Z', country: 'Saudi Arabia', flag: '🇸🇦' },
  { prefix: '7O', country: 'Yemen', flag: '🇾🇪' },
  { prefix: 'EP', country: 'Iran', flag: '🇮🇷' },
  { prefix: 'YI', country: 'Iraq', flag: '🇮🇶' },

  // --- Asia ---
  { prefix: 'JA', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JE', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JF', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JG', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JH', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JI', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JJ', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JK', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JL', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JM', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JN', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JO', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JP', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JQ', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JR', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'JS', country: 'Japan', flag: '🇯🇵' },
  { prefix: 'HL', country: 'South Korea', flag: '🇰🇷' },
  { prefix: '6K', country: 'South Korea', flag: '🇰🇷' },
  { prefix: '6L', country: 'South Korea', flag: '🇰🇷' },
  { prefix: '6M', country: 'South Korea', flag: '🇰🇷' },
  { prefix: '6N', country: 'South Korea', flag: '🇰🇷' },
  { prefix: 'DS', country: 'South Korea', flag: '🇰🇷' },
  { prefix: 'DT', country: 'South Korea', flag: '🇰🇷' },
  { prefix: 'BY', country: 'China', flag: '🇨🇳' },
  { prefix: 'BG', country: 'China', flag: '🇨🇳' },
  { prefix: 'BH', country: 'China', flag: '🇨🇳' },
  { prefix: 'BI', country: 'China', flag: '🇨🇳' },
  { prefix: 'BD', country: 'China', flag: '🇨🇳' },
  { prefix: 'BA', country: 'China', flag: '🇨🇳' },
  { prefix: 'BV', country: 'Taiwan', flag: '🇹🇼' },
  { prefix: 'BM', country: 'Taiwan', flag: '🇹🇼' },
  { prefix: 'BU', country: 'Taiwan', flag: '🇹🇼' },
  { prefix: 'BX', country: 'Taiwan', flag: '🇹🇼' },
  { prefix: 'VR', country: 'Hong Kong', flag: '🇭🇰' },
  { prefix: 'XX9', country: 'Macau', flag: '🇲🇴' },
  { prefix: '9V', country: 'Singapore', flag: '🇸🇬' },
  { prefix: '9M2', country: 'West Malaysia', flag: '🇲🇾' },
  { prefix: '9M6', country: 'East Malaysia', flag: '🇲🇾' },
  { prefix: '9M8', country: 'East Malaysia', flag: '🇲🇾' },
  { prefix: 'HS', country: 'Thailand', flag: '🇹🇭' },
  { prefix: 'E2', country: 'Thailand', flag: '🇹🇭' },
  { prefix: 'XV', country: 'Vietnam', flag: '🇻🇳' },
  { prefix: '3W', country: 'Vietnam', flag: '🇻🇳' },
  { prefix: 'XU', country: 'Cambodia', flag: '🇰🇭' },
  { prefix: 'XW', country: 'Laos', flag: '🇱🇦' },
  { prefix: 'XZ', country: 'Myanmar', flag: '🇲🇲' },
  { prefix: 'DU', country: 'Philippines', flag: '🇵🇭' },
  { prefix: 'DV', country: 'Philippines', flag: '🇵🇭' },
  { prefix: 'DW', country: 'Philippines', flag: '🇵🇭' },
  { prefix: 'DX', country: 'Philippines', flag: '🇵🇭' },
  { prefix: 'DY', country: 'Philippines', flag: '🇵🇭' },
  { prefix: 'DZ', country: 'Philippines', flag: '🇵🇭' },
  { prefix: 'YB', country: 'Indonesia', flag: '🇮🇩' },
  { prefix: 'YC', country: 'Indonesia', flag: '🇮🇩' },
  { prefix: 'YD', country: 'Indonesia', flag: '🇮🇩' },
  { prefix: 'YE', country: 'Indonesia', flag: '🇮🇩' },
  { prefix: 'YF', country: 'Indonesia', flag: '🇮🇩' },
  { prefix: 'YG', country: 'Indonesia', flag: '🇮🇩' },
  { prefix: 'YH', country: 'Indonesia', flag: '🇮🇩' },
  { prefix: '9M4', country: 'Spratly Islands', flag: '🇲🇾' },
  { prefix: 'V8', country: 'Brunei', flag: '🇧🇳' },
  { prefix: 'VU', country: 'India', flag: '🇮🇳' },
  { prefix: 'AT', country: 'India', flag: '🇮🇳' },
  { prefix: 'AU', country: 'India', flag: '🇮🇳' },
  { prefix: 'AW', country: 'India', flag: '🇮🇳' },
  { prefix: 'S2', country: 'Bangladesh', flag: '🇧🇩' },
  { prefix: '4S', country: 'Sri Lanka', flag: '🇱🇰' },
  { prefix: '9N', country: 'Nepal', flag: '🇳🇵' },
  { prefix: 'A5', country: 'Bhutan', flag: '🇧🇹' },
  { prefix: 'AP', country: 'Pakistan', flag: '🇵🇰' },
  { prefix: 'JT', country: 'Mongolia', flag: '🇲🇳' },
  { prefix: 'JU', country: 'Mongolia', flag: '🇲🇳' },
  { prefix: 'JV', country: 'Mongolia', flag: '🇲🇳' },

  // --- Oceania ---
  { prefix: 'VK', country: 'Australia', flag: '🇦🇺' },
  { prefix: 'AX', country: 'Australia', flag: '🇦🇺' },
  { prefix: 'VK9', country: 'Norfolk Island', flag: '🇳🇫' },
  { prefix: 'VK0', country: 'Macquarie Island', flag: '🇦🇺' },
  { prefix: 'ZL', country: 'New Zealand', flag: '🇳🇿' },
  { prefix: 'ZM', country: 'New Zealand', flag: '🇳🇿' },
  { prefix: 'ZK3', country: 'Tokelau', flag: '🇹🇰' },
  { prefix: 'E5', country: 'Cook Islands', flag: '🇨🇰' },
  { prefix: 'A3', country: 'Tonga', flag: '🇹🇴' },
  { prefix: '5W', country: 'Samoa', flag: '🇼🇸' },
  { prefix: '3D2', country: 'Fiji', flag: '🇫🇯' },
  { prefix: 'YJ', country: 'Vanuatu', flag: '🇻🇺' },
  { prefix: 'H4', country: 'Solomon Islands', flag: '🇸🇧' },
  { prefix: 'P2', country: 'Papua New Guinea', flag: '🇵🇬' },
  { prefix: 'V6', country: 'Micronesia', flag: '🇫🇲' },
  { prefix: 'V7', country: 'Marshall Islands', flag: '🇲🇭' },
  { prefix: 'T8', country: 'Palau', flag: '🇵🇼' },
  { prefix: 'T3', country: 'Kiribati', flag: '🇰🇮' },
  { prefix: 'T2', country: 'Tuvalu', flag: '🇹🇻' },
  { prefix: 'C2', country: 'Nauru', flag: '🇳🇷' },
  { prefix: 'FK', country: 'New Caledonia', flag: '🇳🇨' },
  { prefix: 'FO', country: 'French Polynesia', flag: '🇵🇫' },
  { prefix: 'FW', country: 'Wallis & Futuna', flag: '🇼🇫' },

  // --- Africa ---
  { prefix: 'ZS', country: 'South Africa', flag: '🇿🇦' },
  { prefix: 'ZR', country: 'South Africa', flag: '🇿🇦' },
  { prefix: 'ZT', country: 'South Africa', flag: '🇿🇦' },
  { prefix: 'ZU', country: 'South Africa', flag: '🇿🇦' },
  { prefix: '5Z', country: 'Kenya', flag: '🇰🇪' },
  { prefix: '5H', country: 'Tanzania', flag: '🇹🇿' },
  { prefix: '5X', country: 'Uganda', flag: '🇺🇬' },
  { prefix: '9J', country: 'Zambia', flag: '🇿🇲' },
  { prefix: 'Z2', country: 'Zimbabwe', flag: '🇿🇼' },
  { prefix: '7Q', country: 'Malawi', flag: '🇲🇼' },
  { prefix: 'C9', country: 'Mozambique', flag: '🇲🇿' },
  { prefix: 'V5', country: 'Namibia', flag: '🇳🇦' },
  { prefix: 'A2', country: 'Botswana', flag: '🇧🇼' },
  { prefix: '7P', country: 'Lesotho', flag: '🇱🇸' },
  { prefix: '3DA', country: 'Eswatini', flag: '🇸🇿' },
  { prefix: 'D2', country: 'Angola', flag: '🇦🇴' },
  { prefix: '9U', country: 'Burundi', flag: '🇧🇮' },
  { prefix: '9X', country: 'Rwanda', flag: '🇷🇼' },
  { prefix: '9Q', country: 'DR Congo', flag: '🇨🇩' },
  { prefix: 'TN', country: 'Congo', flag: '🇨🇬' },
  { prefix: 'TT', country: 'Chad', flag: '🇹🇩' },
  { prefix: 'TL', country: 'Central African Republic', flag: '🇨🇫' },
  { prefix: 'TJ', country: 'Cameroon', flag: '🇨🇲' },
  { prefix: 'TR', country: 'Gabon', flag: '🇬🇦' },
  { prefix: '3C', country: 'Equatorial Guinea', flag: '🇬🇶' },
  { prefix: 'S9', country: 'São Tomé & Príncipe', flag: '🇸🇹' },
  { prefix: 'ET', country: 'Ethiopia', flag: '🇪🇹' },
  { prefix: 'J2', country: 'Djibouti', flag: '🇩🇯' },
  { prefix: 'T5', country: 'Somalia', flag: '🇸🇴' },
  { prefix: 'ST', country: 'Sudan', flag: '🇸🇩' },
  { prefix: 'SU', country: 'Egypt', flag: '🇪🇬' },
  { prefix: '5A', country: 'Libya', flag: '🇱🇾' },
  { prefix: '5T', country: 'Mauritania', flag: '🇲🇷' },
  { prefix: 'CN', country: 'Morocco', flag: '🇲🇦' },
  { prefix: '7X', country: 'Algeria', flag: '🇩🇿' },
  { prefix: '3V', country: 'Tunisia', flag: '🇹🇳' },
  { prefix: '6W', country: 'Senegal', flag: '🇸🇳' },
  { prefix: 'C5', country: 'The Gambia', flag: '🇬🇲' },
  { prefix: '3X', country: 'Guinea', flag: '🇬🇳' },
  { prefix: 'EL', country: 'Liberia', flag: '🇱🇷' },
  { prefix: '5U', country: 'Niger', flag: '🇳🇪' },
  { prefix: '5V', country: 'Togo', flag: '🇹🇬' },
  { prefix: 'TY', country: 'Benin', flag: '🇧🇯' },
  { prefix: '9G', country: 'Ghana', flag: '🇬🇭' },
  { prefix: 'TU', country: 'Ivory Coast', flag: '🇨🇮' },
  { prefix: 'XT', country: 'Burkina Faso', flag: '🇧🇫' },
  { prefix: 'TZ', country: 'Mali', flag: '🇲🇱' },
  { prefix: '6V', country: 'Senegal', flag: '🇸🇳' },
  { prefix: '5N', country: 'Nigeria', flag: '🇳🇬' },
  { prefix: 'D4', country: 'Cape Verde', flag: '🇨🇻' },
  { prefix: 'D6', country: 'Comoros', flag: '🇰🇲' },
  { prefix: '5R', country: 'Madagascar', flag: '🇲🇬' },
  { prefix: '3B', country: 'Mauritius', flag: '🇲🇺' },
  { prefix: 'S7', country: 'Seychelles', flag: '🇸🇨' },
  { prefix: 'ZD7', country: 'St. Helena', flag: '🇸🇭' },
  { prefix: 'ZD8', country: 'Ascension Island', flag: '🇸🇭' },
  { prefix: 'ZD9', country: 'Tristan da Cunha', flag: '🇸🇭' },
];
